### ISSUE TITLE
gradle中的多项目构建由一个根项目和一个或多个子项目组成，这些子项目也可能包含子项目

### ISSUE THREAD

**Issue by ghostman-git** [GradleCN/GradleSide#15]
![image](https://user-images.githubusercontent.com/13376074/58315444-28dda100-7e44-11e9-8916-6aec0add5773.png)
这种子项目也可能包含子项目的在idea中怎么构建？

**Comment by xingguang2013** [comment]
我也在找寻这样的例子，可是没有找到，暂时是把项目结构打平了

**Comment by pkaq** [comment]
@ghostman-git @xingguang2013 
https://github.com/GradleCN/GradleSide/tree/master/09-multi-project
