### ISSUE TITLE
在执行gradle build时如何同时执行自定义的task？

### ISSUE THREAD

**Issue by Var-iazioni** [GradleCN/GradleSide#18]
我有一个多模块Spring Boot的工程，并且子工程均引用了'org.springframework.boot'插件，目录结构如下
/projectA
/projectA/serviceA
/projectA/serviceB
/projectA/serviceC
在projectA目录执行gradle build时，分别会在三个子工程的build/libs目录下生成jar包。
现在我想将打好的jar包统一复制到某个路径，并且我在/projectA/build.gradle中添加了如下代码：
```
allprojects {
    task copy () {
        doLast { task ->
	    copyJars() {
                CopySpec copySpec ->
                    from "${project.getBuildDir()}\\libs"
                    into "D:\\"  
            }
        }
    }
}
```
此时，在/projectA目录下执行gradle copy，即可将三个子工程的jar包复制到D盘根目录下。

需求是这样的，我希望在/projectA目录下执行gradle build时，在编译打包完成后自动执行copy任务，应该如何编写build.gradle文件？

gradle版本为5.5

**Comment by pkaq** [comment]
```groovy
apply plugin: 'war'
webAppDirName = 'WebRoot'
version = ''
ext{
	targetDir = "F:/Target/war"
}
war{
	baseName ="CMES"
}
task getwar(overwrite: true,dependsOn: war) <<{
	//复制war
	copy{
		from 'build/libs/'
		into "$targetDir"
	}
}
```

祭出一段上古脚本 新版把 << 语法糖换成 dolast写法即可
原理就是让复制任务依赖前置任务 执行的时候直接调用复制任务即可

**Comment by gltncx11** [comment]
> ```groovy
> apply plugin: 'war'
> webAppDirName = 'WebRoot'
> version = ''
> ext{
> 	targetDir = "F:/Target/war"
> }
> war{
> 	baseName ="CMES"
> }
> task getwar(overwrite: true,dependsOn: war) <<{
> 	//复制war
> 	copy{
> 		from 'build/libs/'
> 		into "$targetDir"
> 	}
> }
> ```
> 
> 祭出一段上古脚本 新版把 << 语法糖换成 dolast写法即可
> 原理就是让复制任务依赖前置任务 执行的时候直接调用复制任务即可

这个在gradle build时会执行相应task吗

**Comment by gltncx11** [comment]
> 我有一个多模块Spring Boot的工程，并且子工程均引用了'org.springframework.boot'插件，目录结构如下
> /projectA
> /projectA/serviceA
> /projectA/serviceB
> /projectA/serviceC
> 在projectA目录执行gradle build时，分别会在三个子工程的build/libs目录下生成jar包。
> 现在我想将打好的jar包统一复制到某个路径，并且我在/projectA/build.gradle中添加了如下代码：
> 
> ```
> allprojects {
>     task copy () {
>         doLast { task ->
> 	    copyJars() {
>                 CopySpec copySpec ->
>                     from "${project.getBuildDir()}\\libs"
>                     into "D:\\"  
>             }
>         }
>     }
> }
> ```
> 
> 此时，在/projectA目录下执行gradle copy，即可将三个子工程的jar包复制到D盘根目录下。
> 
> 需求是这样的，我希望在/projectA目录下执行gradle build时，在编译打包完成后自动执行copy任务，应该如何编写build.gradle文件？
> 
> gradle版本为5.5

可以这样 build.finalizedBy(copy)
