### ISSUE TITLE
Gradle多模块工程，A工程（Springboot）使用compile project依赖(B)工程，在Idea中正常运行，打包成jar提示找不到符号

### ISSUE THREAD

**Issue by youzhigithub** [GradleCN/GradleSide#2]
使用Gradle多模块开发Spring cloud项目，A工程是个Springboot项目（eureka-server），B工程是个通用工具类的工程（core），A工程依赖B工程（在根项目的build.gradle中配置）
![image](https://user-images.githubusercontent.com/10285758/43556686-9832adb0-9633-11e8-900c-bf96d676a8df.png)，同时在项目的settings文件中配置了依赖
![image](https://user-images.githubusercontent.com/10285758/43556697-ac311a90-9633-11e8-9134-2c142599f1c4.png)
，在idea中运行正常，当将A工程打包成jar运行时提示找不到符号（A工程中使用B工程代码的地方）
![image](https://user-images.githubusercontent.com/10285758/43556773-093d2e2c-9634-11e8-9416-157ffd3d63ce.png)。
以下为配置文件的内容：
**根项目的settings.gradle:**
rootProject.name = 'springcloud'
include 'service-feign'
include 'service-hi'
include 'eureka-server'
include 'service-zuul'
include 'core'

**根项目的build.gradle:**
buildscript {
    ext{
        springBootVersion = '2.0.3.RELEASE'
        springCloudVersion = 'Finchley.RELEASE'
    }
    repositories {
        maven { url "http://maven.aliyun.com/nexus/content/groups/public/" }
        mavenCentral()
        jcenter()
    }
    dependencies {
        classpath("org.springframework.boot:spring-boot-gradle-plugin:${springBootVersion}")
    }
}
allprojects {
    group 'com.su.sc'
    version '1.0.0'

    apply plugin: 'org.springframework.boot'
    apply plugin: 'idea'
    apply plugin: 'java'
}
subprojects{
    apply plugin: 'io.spring.dependency-management'

    sourceCompatibility = 1.8

    repositories {
        maven { url "http://maven.aliyun.com/nexus/content/groups/public/" }
        mavenCentral()
        jcenter()
    }

    [compileJava,compileTestJava,javadoc]*.options*.encoding = 'UTF-8'

    dependencies {
        compile('org.springframework.boot:spring-boot-starter')
        compile('javax.servlet:javax.servlet-api:3.1.0')
        compile group: 'com.alibaba', name: 'fastjson', version: '1.2.47'

        compile(project(':core'))
        testCompile "org.springframework.boot:spring-boot-starter-test"
    }

    dependencyManagement {
        imports {
            mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}"
        }
    }

}

**A项目的build.gradle(eureka-server)**
dependencies {
    compile('org.springframework.cloud:spring-cloud-starter-netflix-eureka-client')
    compile('org.springframework.boot:spring-boot-starter-web')
}
**B项目的build.gradle(core)**

dependencies {

}
configurations {
    all*.exclude module: 'core'
}

打包方式为：
1、idea中选择任务
![image](https://user-images.githubusercontent.com/10285758/43556892-a3e010ac-9634-11e8-95a3-70ac41899096.png)
2、到A项目跟目录使用命令行:gradle build打包

**Comment by pkaq** [comment]
@youzhigithub B项目不要all exclude

**Comment by youzhigithub** [comment]
@pkaq  没有效果，依然报错。为了防止缓存，我重新起了一个项目。
A项目的配置：
![image](https://user-images.githubusercontent.com/10285758/43693251-8565af46-995f-11e8-8b79-88717739afc7.png)
B项目的配置：
![image](https://user-images.githubusercontent.com/10285758/43693270-9680b852-995f-11e8-9a4c-50b5d2b98881.png)

**Comment by pkaq** [comment]
a依赖b 但b要把自身排除掉 而不是全局排除

**Comment by youzhigithub** [comment]
@pkaq  我现在不是在打包的时候找不到B项目的代码吗？ 还需要把B项目排除？
common是现在的B项目，我这样配置后去打包依然报错呀，配置不对嘛
![image](https://user-images.githubusercontent.com/10285758/43699469-73dac776-9981-11e8-9d1e-d7941d5a1e06.png)

**Comment by pkaq** [comment]
其它可以依赖core  但core不要依赖core 循环依赖了  直接上可重现链接吧

**Comment by youzhigithub** [comment]
@pkaq https://github.com/youzhigithub/springcloud-demo  老哥这是demo地址，尝试打包service-hi的时候失败

**Comment by pkaq** [comment]
刚好我这有个sc的示例 参考一下
https://github.com/pkaq/springcloud7

**Comment by shirayner** [comment]
> 这个示例没有出现项目依赖..

老哥，我也出现了这个问题，请问您解决了吗？

**Comment by iSayCheese** [comment]
请问老哥解决这个问题了么？

**Comment by iSayCheese** [comment]
> 这个示例没有出现项目依赖..

请问老哥解决这个问题了么？

**Comment by shirayner** [comment]
今天再问一遍，老哥解决了吗

**Comment by TomorJM** [comment]
同问hh

**Comment by pkaq** [comment]
各种结构的多模块项目示例
https://github.com/GradleCN/GradleSide/tree/master/09-multi-project
